### ISSUE TITLE
File gone rogue?

### ISSUE THREAD

**Issue by Peyton2017** [sca1998/P2PChat#1]
I open file 64, and this is what I get. Also, windows sees it has "file"
![Capture](https://user-images.githubusercontent.com/28621717/55565033-f3bb9a80-56ad-11e9-9c69-4743b8a5cb03.PNG)

**Comment by chris-susantooo** [comment]
Hey Peyton2017, room_server_64 is a binary executable, unfortunately there is no source code given.
If you are using windows, you may want to install Windows Subsystem for Linux, then open the file with Linux shell:
  
![image](https://user-images.githubusercontent.com/16538634/55565415-5f444d00-572c-11e9-926c-038392c3cddf.png)

The P2PChat client program, however, is given as the task. The source file is available in the repo.
